<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150903/1-150Z3201914.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150903/1-150Z3201914.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="597";
$z[1][4]['height']="419";
$z[2]=Array("img"," /uploads/allimg/150903/1-150Z3201915.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/150903/1-150Z3201915.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="600";
$z[2][4]['height']="420";
$z[3]=Array("img"," /uploads/allimg/150903/1-150Z3201915-50.jpg ",387,538);
$z[3][4]['ddimg']="/uploads/allimg/150903/1-150Z3201915-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="597";
$z[3][4]['height']="374";
$z[4]=Array("img"," /uploads/allimg/150903/1-150Z3201915-51.jpg ",540,691);
$z[4][4]['ddimg']="/uploads/allimg/150903/1-150Z3201915-51.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="581";
$z[4][4]['height']="406";
$z[5]=Array("img"," /uploads/allimg/150903/1-150Z3201916.jpg ",693,838);
$z[5][4]['ddimg']="/uploads/allimg/150903/1-150Z3201916.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="651";
$z[5][4]['height']="441";

?>