{dede:sppage sptype='full' sptype='full' srul='1' erul='5'}{/dede:sppage}
{dede:previewurl}http://www.cbj1998.com/Products/smyqdbtytx.html{/dede:previewurl}
{dede:keywordtrim}{/dede:keywordtrim}
{dede:descriptiontrim}{/dede:descriptiontrim}
{dede:item field='title' value='' isunit='' isdown=''}
   {dede:match}var OBJ_TITLE = "[内容]";
//视频关键词{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='writer' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='source' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='pubdate' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}@me=GetMkTime(@me);{/dede:function}
{/dede:item}
{dede:item field='cc' value='' isunit='' isdown=''}
   {dede:match}<br/>尺寸：[内容]<br/>颜色{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='ys' value='' isunit='' isdown=''}
   {dede:match}<br/>颜色：[内容]<br/>材质{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='cz' value='' isunit='' isdown=''}
   {dede:match}<br/>材质：[内容]</div>
    <div class="pd_hotline">{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='imgurls' value='' isunit='1' isdown='1'}
   {dede:match}{/dede:match}
   
   {dede:function}@me=TurnImageTag(@me);{/dede:function}
{/dede:item}
{dede:item field='body' value='' isunit='1' isdown='1'}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
