<?php
$z[0]=Array("field","上海办公家具,上海办公家",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","上海办公家具公司——碧江家具,专注于中高端办公家具销售生产16年,斥巨资引进国际先进生产设备,年综合产值达到10亿元,独家打造上海第一家线下办公家具体验馆。您可以先体验后购买",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","董事长办公桌——迪盛U04D38-1 U04D32-1",368,453);
$z[2][4]['name']="title";
$z[3]=Array("field","",455,494);
$z[3][4]['name']="writer";
$z[4]=Array("field","",496,535);
$z[4][4]['name']="source";
$z[5]=Array("field","定制",537,578);
$z[5][4]['name']="cc";
$z[6]=Array("field","更多颜色选择可参考色板",580,648);
$z[6][4]['name']="ys";
$z[7]=Array("field","进口板材、进口木皮贴面，符合国家E1环保要求的亚创高度纤维板。",650,774);
$z[7][4]['name']="cz";
$z[8]=Array("field","",776,813);
$z[8][4]['name']="body";
$z[9]=Array("field","",815,855);
$z[9][4]['name']="pubdate";
$z[10]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",857,1121);
$z[10][4]['name']="imgurls";
$z[11]=Array("field","/uploads/allimg/c150903/14412JG1250-234J.jpg",1123,1206);
$z[11][4]['name']="litpic";

?>