{dede:field name='keywords'}上海办公家具,上海办公家{/dede:field}
{dede:field name='description'}上海办公家具公司——碧江家具,专注于中高端办公家具销售生产16年,斥巨资引进国际先进生产设备,年综合产值达到10亿元,独家打造上海第一家线下办公家具体验馆。您可以先体验后购买{/dede:field}
{dede:field name='title'}董事长办公桌——迪盛U04D38-1 U04D32-1{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='cc'}定制{/dede:field}
{dede:field name='ys'}更多颜色选择可参考色板{/dede:field}
{dede:field name='cz'}进口板材、进口木皮贴面，符合国家E1环保要求的亚创高度纤维板。{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150903/14412JG1250-234J.jpg{/dede:field}
