{dede:noteinfo notename="产品中心" channelid="2" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="http://wpa.qq.com" listpic="1" usemore="0"}
    {dede:addurls}http://www.cbj1998.com/smyqb.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="pro_main"> 
                
                        <dl class="pd_list_dl">{/dede:areastart}
    {dede:areaend}<div id="pagerMain" class="apage">{/dede:areaend}
{/dede:listrule}
