<?php
$z[0]=Array("field","办公家具,上海办公家具",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","上海碧江家具有限公司拥有16年行业经验,提供办公家具,办公椅,会议桌,办公桌,上海办公家具等，是您首选的办公家具厂家-联系热线：400-886-2028",74,306);
$z[1][4]['name']="description";
$z[2]=Array("field","实木油漆办公桌",308,367);
$z[2][4]['name']="title";
$z[3]=Array("field","",369,408);
$z[3][4]['name']="writer";
$z[4]=Array("field","",410,449);
$z[4][4]['name']="source";
$z[5]=Array("field","定制",451,492);
$z[5][4]['name']="cc";
$z[6]=Array("field","更多颜色选择可参考色板",494,562);
$z[6][4]['name']="ys";
$z[7]=Array("field","进口板材、进口木皮贴面，符合国家E1环保要求的亚创高度纤维板。",564,688);
$z[7][4]['name']="cz";
$z[8]=Array("field","",690,727);
$z[8][4]['name']="body";
$z[9]=Array("field","",729,769);
$z[9][4]['name']="pubdate";
$z[10]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",771,1035);
$z[10][4]['name']="imgurls";
$z[11]=Array("field","/uploads/allimg/c150903/14412JG4320-453W.jpg",1037,1120);
$z[11][4]['name']="litpic";

?>