{dede:field name='keywords'}办公家具,上海办公家具{/dede:field}
{dede:field name='description'}上海碧江家具有限公司拥有16年行业经验,提供办公家具,办公椅,会议桌,办公桌,上海办公家具等，是您首选的办公家具厂家-联系热线：400-886-2028{/dede:field}
{dede:field name='title'}实木油漆大班台——御泰系列 U604D32 U604D28{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='cc'}定制{/dede:field}
{dede:field name='ys'}更多颜色选择可参考色板{/dede:field}
{dede:field name='cz'}进口板材、进口木皮贴面，符合国家E1环保要求的亚创高度纤维板。{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150903/14412JH0260-24R4.jpg{/dede:field}
