<?php
$z[0]=Array("global","",508,540);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",668,700);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",790,812);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("channel","\r\n<li><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n",928,1132);
$z[3][4]['type']="top";
$z[3][4]['row']="9";
$z[3][4]['currentstyle']="<li class='cur1'><a href='~typelink~' >~typename~</a> </li>";
$z[4]=Array("channelartlist","<a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>|",1554,1720);
$z[4][4]['typeid']="15";

?>