<?php
$z[0]=Array("global","",502,534);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",659,691);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",781,803);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("channel","\r\n<li><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n",932,1136);
$z[3][4]['type']="top";
$z[3][4]['row']="9";
$z[3][4]['currentstyle']="<li class='cur1'><a href='~typelink~' >~typename~</a> </li>";

?>