<?php
$z[0]=Array("channel","\r\n<h4 style=\"margin-bottom:10px;\"><a title='[field:typename/]' href=\"[field:typelink/]\" >[field:typename/]</a></h4>\r\n",128,274);
$z[1]=Array("global","",676,708);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",736,757);
$z[2][4]['name']="cfg_mc";
$z[3]=Array("global","",795,817);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",854,875);
$z[4][4]['name']="cfg_sj";
$z[5]=Array("global","",908,929);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("global","",960,981);
$z[6][4]['name']="cfg_yx";
$z[7]=Array("global","",1018,1039);
$z[7][4]['name']="cfg_dz";

?>