<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\" >按材质分类</a>",130,213);
$z[0][4]['typeid']="55";
$z[1]=Array("channel","\r\n<h5 class='erji'><a class=\"ershow\" title='[field:typename/]' href=\"[field:typelink/]\" >[field:typename/]</a></h5>\r\n",227,385);
$z[1][4]['typeid']="55";
$z[2]=Array("type","<a href=\"[field:typelink/]\" >按类型分类</a>",399,482);
$z[2][4]['typeid']="13";
$z[3]=Array("channel","\r\n<h5 class='erji'><a class=\"ershow\" title='[field:typename/]' href=\"[field:typelink/]\" >[field:typename/]</a></h5>\r\n",496,654);
$z[3][4]['typeid']="13";
$z[4]=Array("type","<a href=\"[field:typelink/]\" >按单位性质分类</a>",668,757);
$z[4][4]['typeid']="15";
$z[5]=Array("channel","\r\n<h5 class='erji'><a class=\"ershow\" title='[field:typename/]' href=\"[field:typelink/]\" >[field:typename/]</a></h5>\r\n",771,929);
$z[5][4]['typeid']="15";
$z[6]=Array("global","",1337,1369);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1397,1418);
$z[7][4]['name']="cfg_mc";
$z[8]=Array("global","",1456,1478);
$z[8][4]['name']="cfg_tel";
$z[9]=Array("global","",1515,1536);
$z[9][4]['name']="cfg_sj";
$z[10]=Array("global","",1569,1590);
$z[10][4]['name']="cfg_qq";
$z[11]=Array("global","",1621,1642);
$z[11][4]['name']="cfg_yx";
$z[12]=Array("global","",1679,1700);
$z[12][4]['name']="cfg_dz";

?>